-- seed tickets for OpsGuardian (H2)
INSERT INTO TICKETS (ID, TITLE, DESCRIPTION, REPORTER, PRIORITY, CATEGORY, STATUS, CREATED_AT) VALUES
                                                                                                   (1,'Database connection failed','Application reports DB connection timeout when fetching orders','alice@example.com','P0','Database','OPEN', CURRENT_TIMESTAMP()),
                                                                                                   (2,'Login page error','Users receive 500 when trying to login','bob@example.com','P1','Application','OPEN', CURRENT_TIMESTAMP()),
                                                                                                   (3,'Password reset not working','Password reset emails not delivered','charlie@example.com','P2','Access','OPEN', CURRENT_TIMESTAMP()),
                                                                                                   (4,'Intermittent high latency','Service latency spikes on checkout','dan@example.com','P1','Application','OPEN', CURRENT_TIMESTAMP()),
                                                                                                   (5,'New user provisioning fails','Onboarding script fails for several users','ema@example.com','P2','Access','OPEN', CURRENT_TIMESTAMP()),
                                                                                                   (6,'Disk space low on DB node','DB node disk usage 95% alerts','frank@example.com','P0','Database','OPEN', CURRENT_TIMESTAMP()),
                                                                                                   (7,'Payment gateway timeout','Payments failing intermittently','grace@example.com','P1','Network','OPEN', CURRENT_TIMESTAMP()),
                                                                                                   (8,'Service health check failing','Health check returns 503 sporadically','henry@example.com','P1','Application','OPEN', CURRENT_TIMESTAMP()),
                                                                                                   (9,'Duplicate order creation','Orders duplicated after retry','irene@example.com','P2','Application','OPEN', CURRENT_TIMESTAMP()),
                                                                                                   (10,'VPN access blocked','Remote worker cannot access internal resources','jack@example.com','P1','Network','OPEN', CURRENT_TIMESTAMP());
